### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by TheMcMurder** [single-spa/single-spa.js.org#164]
We need to upgrade to circle CI 2.0 to get the deploys working again.

https://circleci.com/gh/single-spa/single-spa.js.org/509

**Comment by internettrans** [comment]
I'm confused because it looks like we are already using circleci@2

https://github.com/single-spa/single-spa.js.org/blob/1175ab997f375f8c8de410649fe68b1f31e69779/.circleci/config.yml#L1

Furthermore, I ran `circleci config validate` [as instructed here](https://circleci.com/docs/2.0/local-cli/#validate-a-circleci-config), and it says that we're good.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/5524384/74299033-b3cf3600-4d08-11ea-8325-15d6bc081cee.png">

I've raised a support ticket with CircleCI to diagnose further. If anyone sees anything I'm missing, let me know - I imagine CircleCI will take a few days to respond.

<img width="1577" alt="image" src="https://user-images.githubusercontent.com/5524384/74299278-67382a80-4d09-11ea-86de-8df74e11a5e5.png">

**Comment by internettrans** [comment]
This was a false alarm - only the builds on the `gh-pages` branch are failing. The builds on the master branch are fine.

I've asked CircleCI support for ideas on how to turn off CircleCI entirely for the `gh-pages` branch.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/5524384/74303631-c735cd80-4d17-11ea-9d53-b8a0d8717fb2.png">
