### ISSUE TITLE
Translate documentation into Portuguese

### ISSUE THREAD

**Issue by mstrlaw** [single-spa/single-spa.js.org#183]

**Comment by internettrans** [comment]
# Technical tasks

- [x] Decide on a language code to use. I would propose `pt-pt`, since my understanding is that you and your team are based in Portugal. The React translations have both `pt-pt` and `pt-br` a separate translations, for portugal and brazil.
- [x] Create a new repo called `pt-pt.single-spa.js.org`. **Manually** initialize it to be the same git tree as single-spa.js.org. Do not do this by forking the repo -- a fork has a separate git tree. You can do this by initializing to empty repo (no readme, no gitignore) and then adding that as a remote to your local copy of `single-spa.js.org`:
```sh
cd single-spa.js.org
git remote add pt-pt git@github.com:single-spa/pt-pt.single-spa.js.org.git
git push pt-pt master:master
```
- [x] Set up the bot to automatically commit to pt-pt.single-spa.js.org whenever a PR is merged into single-spa.js.org. When a merge conflict happens, a pull request is created instead of a commit to master. We're currently doing this with https://github.com/guguji5/sync-fork-repo, but i don't think it is yet set up to handle more repos besides the `zh-hans` repo. @guguji5 can you clarify? Perhaps should we transfer that repository into https://github.com/single-spa so that it's owned and managed by you, the single-spa core team, and other translators.
- [x] Update docusaurus config to correct domain
- [x] Update CircleCI badge in readme to correct url
- [x] Enable builds in CircleCI. Add the GITHUB_TOKEN env variable
- [x] Modify [`/website/static/CNAME`](https://github.com/single-spa/single-spa.js.org/blob/master/website/static/CNAME) in to be the correct domain.
- [ ] Force HTTPS in the repository settings in Github. This takes a day or so after the CNAME is set for the SSL cert to be set up.
- [x] Create a pull request to the js.org repo, adding the subdomain. Should be similar to this: https://github.com/js-org/js.org/pull/3747
- [x] Add portuguese to [translations.js](https://github.com/single-spa/single-spa.js.org/blob/master/website/src/data/languages.js), so that it appears in the list at https://single-spa.js.org/languages

# Organizational tasks

- [ ] Find at least one other person besides @mstrlaw who can help with the translations.
- [x] Evaluate time commitment of maintaining the translations.
- [ ] Translate the files `/website/versioned_docs/version-5.x` directory. Do not translate the `/docs` directory. Also, translate each of the pages in `/website/pages`

**Comment by internettrans** [comment]
@mstrlaw can you confirm that you're up for this? And that you agree that `pt-pt` makes the most sense for the subdomain?

If so, I'll go ahead and create an empty repo for it and give you write access to start working on it.

**Comment by mstrlaw** [comment]
Hey @joeldenning 

I'm up for it. I think I can bring at least someone else to assist in the translation. Pt-pt is indeed the right code. You can go ahead and create the repo 👍

**Comment by internettrans** [comment]
I've created the repo: https://github.com/single-spa/pt-pt.single-spa.js.org

Also, I've invited you to the repo, you can accept it at https://github.com/single-spa.

Finally, I've made a few of the modifications already and checked the corresponding checkboxes above. If you could work on getting the first deployment successful in CircleCI, that would be great, and then the other checkboxes too. I've given you access to this repository as well, so I think you should be able to check the checkboxes in my message, too.

**Comment by guguji5** [comment]
I will help to set the sync script up. the bot account (single-spa-bot) need the permission of push code, too.

**Comment by internettrans** [comment]
Thanks @guguji5 - it looks like the bot is working for pt-pt now? I see it made a commit recently:

![image](https://user-images.githubusercontent.com/5524384/75277576-7d43f180-57c5-11ea-80bb-877cef4659a3.png)

**Comment by guguji5** [comment]
@joeldenning Yes, it is working for multiple languages, I fix the bug that could not create PR successfully. After detecting the result for several days, I will transfer the ownership to this account.

**Comment by internettrans** [comment]
Thanks,  guguji for your great work on the bot.

I've created https://github.com/js-org/js.org/pull/3756 to add pt-pt as a subdomain of single-spa.js.org

**Comment by internettrans** [comment]
Also created https://github.com/single-spa/single-spa.js.org/pull/186 to add portuguese to the translations.js file

**Comment by internettrans** [comment]
This is now live! And linked to from https://single-spa.js.org/languages
