### ISSUE TITLE
React Ecosystem SingleSpaContext documentation request

### ISSUE THREAD

**Issue by Kizmar** [single-spa/single-spa.js.org#25]
Documentation request:
https://single-spa.js.org/docs/ecosystem-react.html#singlespacontext

**Comment by frehner** [comment]
Hm, I'm trying to remember what it does... looking at this https://github.com/CanopyTax/single-spa-react/blob/166e48606627fd90b523fca2386ca4a1d33aa118/src/single-spa-react.js

it appears that it wraps the application in a React Context Provider with the customProps you pass to it, so that any child component in the application can consume the customProps using a Context Consumer.

I could be wrong though.

**Comment by Kizmar** [comment]
Is this only available when using `<Parcel />`, or can we pass context when registering an app?

**Comment by frehner** [comment]
So, the Context Provider has as its value the [lifecycle props](https://single-spa.js.org/docs/building-applications.html#lifecyle-props) which optionally include any custom props you give it. 

I know applications get wrapped with the Context Provider, and I think[ Parcels get that too](https://github.com/CanopyTax/single-spa-react/blob/166e48606627fd90b523fca2386ca4a1d33aa118/src/parcel.js#L63) but I haven't tested it to see if it looks the same. 

Currently you can't customize it other than any [custom props](https://single-spa.js.org/docs/building-applications.html#lifecyle-props) you pass. 

There's also a hint of how you use it in the [quickstart example code](https://single-spa.js.org/docs/ecosystem-react.html#quickstart), and you just use it like any other [Context Consumer in React ](https://reactjs.org/docs/context.html#contextconsumer)

**Comment by internettrans** [comment]
Closing this because it's old. Feel free to reopen.
