### ISSUE TITLE
Does single-spa support nextjs?

### ISSUE THREAD

**Issue by xmkan** [single-spa/single-spa.js.org#306]
Just wish to know if single-spa support nextjs and is there any sample codes for integration with nextjs?

**Comment by internettrans** [comment]
Not yet. I've been working on improving the server rendering story for single-spa, but right now it's not great. You can check out https://github.com/namecheap/ilc to see a community maintained set of projects that help with server rendered react microfrontends that use single-spa, but they don't use nextjs.

**Comment by xmkan** [comment]
oh okok, thank you very much!

**Comment by ffleandro** [comment]
Is this still the status for next.js support?

**Comment by internettrans** [comment]
Single-spa server rendering has improved some since my last post - see https://single-spa.js.org/docs/ssr-overview for the recommendations.

NextJS isn't officially supported yet, unfortunately, since NextJS doesn't allow you to control where it mounts itself to the DOM. There are a couple of other challenges with NextJS and microfrontends, as well, that will need to be ironed out. I would like to work on improving support for NextJS, but do not have a timeline for when I'll get to it.

**Comment by sahilhaslani** [comment]
In your https://github.com/isomorphic-microfrontends/trainers project, I see its based on nextjs. Does this mean single spa can load SSR rendered MF from nextjs?

**Comment by internettrans** [comment]
Data Camp has sponsored me to support NextJS with single-spa, so I've been working on it in the last couple of weeks.

**Comment by sourabh8003** [comment]
Hi @joeldenning, Any luck on your work to support NextJS?

**Comment by internettrans** [comment]
Yes I've made some progress, but it's not finished yet. I'll share here when I have updates. I don't have a specific timeline for it.

**Comment by tessy2728** [comment]
Hi @joeldenning, Did you get a chance to make it to support NextJS? I have the same requirement. I am trying out https://github.com/isomorphic-microfrontends/trainers. But, I am getting errors. 
Here is what I am getting when I try to register Next JS application in Single SPA.
vendor.js:43 Uncaught ReferenceError: application 'sample-next' died in status LOADING_SOURCE_CODE: __dirname is not defined
    at index.js:formatted:1
    at Object.../../../node_modules/next/dist/compiled/web-vitals/web-vitals.es5.umd.min.js (index.js:formatted:1)
    at __webpack_require__ (bootstrap:84)
    at Object.../../../node_modules/next/dist/client/performance-relayer.js (index.js:formatted:1)
    at __webpack_require__ (bootstrap:84)
    at Object.../../../node_modules/next/dist/client/index.js (index.js:formatted:1)
    at __webpack_require__ (bootstrap:84)
    at Module.../../sample-next/single-spa/single-spa-next.js (index.js:formatted:1)
    at __webpack_require__ (bootstrap:84)
    at Module.../../sample-next/single-spa/main.js (index.js:formatted:1)

**Comment by internettrans** [comment]
NextJS support is closer, but not finalized. Here’s an update I shared with Data Camp:

The main update is that I have NextJS properly mounting in the browser both when it’s part of the server-rendered content and when it is only mounted due to client side navigation (without having been part of the initial server rendered content.)

Along with that, I am now properly communicating the metadata from NextJS (<meta> <link> <script> etc) between the NextJS server and the root config / orchestrator server. Previously I was embedding the full NextJS <html> document within the existing document for the other microfrontends. Now it’s only embedding bits and pieces of NextJS’ overall document, as needed, rather than the whole thing.

I’ve only worked 8 hours on it, still, unfortunately - the past two months have been perhaps the busiest of my entire career and I bit off a bit more than I could chew. However, things have been calming down more and I will work some more on it this week and in the coming weeks. The good news is that I’ve made some good progress with the little time that I’ve been able to dedicate to it. Much of what I’ve done so far needs polish before it could be used in a production system, but much of the functionality is there

:grey_question:= haven’t investigated it yet
:deep_work: = currently investigating
:building_construction: = Started implementation, but not yet working
:house: = It’s working! Further polish maybe needed, but it’s mostly there.
:done: = completely finished, polished. Highest level of doneness
:nextjs: = Pull Request to NextJS required
:pensive: = not finished investigating, but looking difficult
:dizzy_face: = highest level of concern - I am stuck and don’t know how to proceed.

:done: Share dependencies in-browser (react, react-dom, etc) for perf boost and cross microfrontend import support of React components.
:done: Load NextJS webpack bundle as a SystemJS module in the browser
:done: Verify client-rendered MFEs can blend well with server-rendered NextJS MFEs.
:house: Have root config server make outbound request to nextjs server. Embed HTML into the correct slot in the DOM.
:house: Create single-spa-main.js file in NextJS MFE, which serves as the public interface for SystemJS.
:nextjs: Allow fully qualified basePath in next.config.js, so browser assets come from correct URL. I think I’ll try to put together a pull request to Next for this. I am currently working around this (partially) via root config server redirects whenever it sees _next in the request, but only with exactly one NextJS MFE (not more). See https://nextjs.org/docs/api-reference/next.config.js/basepath
:house: Change SSR hydration to originate from single-spa-main.js rather than node_modules/next/dist/client/index.js.
:house:  Have NextJS communicate its required <link> and <script> tags in a different way than just embedding in HTML. See https://single-spa.js.org/docs/layout-definition#assets for starting point, but there’s more to this - probably pass them via HTTP response headers.
:grey_question: Verify client-side navigation between NextJS pages works properly.
 :house: Verify NextJS app can be fully unmounted client-side (when other MFEs take over for other routes).
:house: Verify remount works.
:house:  verify NextJS app can mount on page where it’s only client rendered - was not part of initial SSR
:grey_question: Production builds
:grey_question: CI/CD for deployments
:grey_question: NextJS head manager is not encapsulated and interfering with other microfrontends.

**Comment by cah-sourabh-singh** [comment]
Thanks for sharing @joeldenning

**Comment by sourabh8003** [comment]
Thanks for sharing @joeldenning

**Comment by hvdson** [comment]
Will there be support for static builds via next export as well?

**Comment by internettrans** [comment]
In the initial support, I've been focused on incorporating dynamic NextJS servers, not on static builds.

**Comment by ey52fpv** [comment]
HI @joeldenning  do you have the latest status on this request?

**Comment by internettrans** [comment]
I haven't worked on it in a while.

**Comment by marcatos** [comment]
Hi @joeldenning,

would you accept collaborations in order to deliver next.js support faster?

**Comment by internettrans** [comment]
Explaining the code to new collaborators would probably take more effort and time than just doing it myself. In the past when I've worked on difficult projects like this with new contributors they end up asking for a lot of my time to help them and then getting disappointed when I do not have that time to give.

A main reason that I haven't worked much on NextJS support is that I don't think the approach I've taken will be very stable or performant, nor do I have much experience with NextJS. The truth is that NextJS isn't very well suited for microfrontends since it has several very hard assumptions built into it that have made things pretty difficult. For example, it is hard coded to mount to `<div id="__next">` and that cannot be configured for multiple microfrontends sharing the page. Additionally, it does not allow for fully qualified urls as the base path for loading frontend assets, which is problematic if you want NextJS to be one of many microfrontends.

I'm the kind of person who gets stressed by dozens / hundreds of people wanting me to work on something. And that stress increases when the project I'm working on isn't one with a good solution and the work I produce will likely only result in their disappointment since it will have lots of limitations and problems. I think that stress I feel is the main reason i've paused working on NextJS support. I may continue it at some point.

**Comment by internettrans** [comment]
If someone would like to try to help out with it, you can try cloning the repos I shared above. However, I am not available to mentor anyone on it and will not help you diagnose or fix things or get them running. I would be open to reviewing pull requests

**Comment by marcatos** [comment]
I understand your frustration @joeldenning, I didn't meant to push you.

We're currently adopting single-spa for a big project and we're evaluating next.js caching capabilities, that's why I would have been happy to give you an helping-hand . We'll try to clone the repo to figure out how to solve some of the known issues.

**Comment by ameerhamza0403** [comment]
Hi @joeldenning  what is the status on support for nextjs in single-spa, did you find time to complete this story ?

**Comment by internettrans** [comment]
No I haven't worked on NextJS support since my last comment.

**Comment by metacoding** [comment]
Any update ?

**Comment by C3sarRC** [comment]
Any update?

**Comment by MuhammadJamaluddin** [comment]
Cough

**Comment by andres-lara-capgemini** [comment]
:D

**Comment by voltuer** [comment]
i'd like to know if this is going to happen, of it anyone knows another microfrontend framework that is compatible with both nextjs and vuejs ❓ 😄

**Comment by bharat5604** [comment]
@sebolio  have you tried module federation?

**Comment by Bala-raj** [comment]
Looking for the same

**Comment by aravsanj** [comment]
Hello, is this a reality today? Anyone?

**Comment by MilanKovacic** [comment]
Hi, Next.js is currently not supported.

**Comment by tangguhriyadi** [comment]
@joeldenning hi, any update for nextjs support ?

**Comment by MilanKovacic** [comment]
Next.js is still not supported.

**Comment by RinNguyens** [comment]
Next.js is still not supported. 🗡️

**Comment by krishna-koushik** [comment]
any update? also is there a PR or a github branch where we can look at these changes?

**Comment by MagedWilliamdevlink** [comment]
i gave up on this project, what a waste

**Comment by MilanKovacic** [comment]
Hi everyone,
At this time, there haven't been any new developments, or plans in regards to Next.js support.
If there are any updates, we will be glad to share them.
If anyone is interested in contributing support for Next, or discussing it, feel free to post in the Slack channel.

**Comment by artursopelnik** [comment]
Next.js is still not supported 👎

**Comment by internettrans** [comment]
NextJS asserts control over the HTML file in a way that conflicts with the single-spa approach of multiple microfrontends sharing an html page and root config. NextJS supports client rendering, prerendering, and server rendering which all would need to be handled differently in a single-spa context. The design of NextJS is not one that is very aligned with microfrontends existing within one SPA. Supporting NextJS would be a huge pain and the single-spa project does not receive enough funding at this time to take on such a large, long-lasting maintenance burden.
