### ISSUE TITLE
Add documentation translation to Spanish

### ISSUE THREAD

**Issue by codesandtags** [single-spa/single-spa.js.org#317]
Hi Single SPA community,

In the company where I work, we started using single SPA for some micro-frontend projects, I think it's a great framework for micro front-end composition/routing, however, there is not documentation for LATAM. 

I would like to know, how to translate the content in Spanish, in order to have more coverage in this region.

Thanks in advance for your time and your answer.

**Comment by internettrans** [comment]
Hi @codesandtags, sure I'd love to have a spanish translation of the website. Do you know of any other people who can help with the translations? I generally prefer having at least two translators instead of one.

Here are the things that need to be done. If you can confirm that there is another person who is interested in helping maintain the translations, we can proceed.

# Technical tasks

- [x] Decide on a language code to use. I would propose `es`
- [x] Create a new repo called `es.single-spa.js.org`. **Manually** initialize it to be the same git tree as single-spa.js.org. Do not do this by forking the repo -- a fork has a separate git tree. You can do this by initializing to empty repo (no readme, no gitignore) and then adding that as a remote to your local copy of `single-spa.js.org`:
```sh
cd single-spa.js.org
git remote add es git@github.com:single-spa/es.single-spa.js.org.git
git push es master:master
```
- [x] Set up the bot to automatically commit to es.single-spa.js.org whenever a PR is merged into single-spa.js.org. When a merge conflict happens, a pull request is created instead of a commit to master. We're currently doing this with https://github.com/guguji5/sync-fork-repo, but i don't think it is yet set up to handle more repos besides the `zh-hans` repo. @guguji5 can you clarify? Perhaps should we transfer that repository into https://github.com/single-spa so that it's owned and managed by you, the single-spa core team, and other translators.
- [x] Update docusaurus config to correct domain
- [x] Update CircleCI badge in readme to correct url
- [x] Enable builds in CircleCI. Add the GITHUB_TOKEN env variable
- [x] Modify [`/website/static/CNAME`](https://github.com/single-spa/single-spa.js.org/blob/master/website/static/CNAME) in to be the correct domain.
- [x] Force HTTPS in the repository settings in Github. This takes a day or so after the CNAME is set for the SSL cert to be set up.
- [x] Create a pull request to the js.org repo, adding the subdomain. Should be similar to this: https://github.com/js-org/js.org/pull/3747
- [x] Add Spanish to [translations.js](https://github.com/single-spa/single-spa.js.org/blob/master/website/src/data/languages.js), so that it appears in the list at https://single-spa.js.org/languages

# Organizational tasks

- [x] Find at least one other person besides @mstrlaw who can help with the translations.
- [x] Evaluate time commitment of maintaining the translations.
- [x] Translators watch the Github repository for all activity
- [ ] Translate the files `/website/versioned_docs/version-5.x` directory. Do not translate the `/docs` directory. Also, translate each of the pages in `/website/pages`

**Comment by codesandtags** [comment]
Hi @joeldenning ,

I'm glad to read your answer, I have a couple of friends who would have really happy to help with the translation.
By the way, our native language is Spanish (Colombia), so I think we could do a good job. In the meantime, we could get more people from other countries to contribute to those tasks.

At the beginning @crorodriguezro and me could start working in the translation.

Cheers!

Edwin

**Comment by internettrans** [comment]
Great - I will start working on some of the tasks later today and will give you and @crorodriguezro access to the new repo.

One thing - I believe that `es` is the best country code for this? We probably don't need to differentiate between `es-es`, `es-mx`, `es-co`, etc?

**Comment by codesandtags** [comment]
That's right!

Only `es` is enough, we don't need to differentiate the countries.

**Comment by codesandtags** [comment]
> Hi @joeldenning ,
> 
> I'm glad to read your answer, I have a couple of friends who would have really happy to help with the translation.
> By the way, our native language is Spanish (Colombia), so I think we could do a good job. In the meantime, we could get more people from other countries to contribute to those tasks.
> 
> At the beginning @crorodriguezro and me could start working in the translation.
> 
> Cheers!
> 
> Edwin

@joeldenning , Just to confirm @diegohoyos also can help us 💪🏼.

**Comment by internettrans** [comment]
I have created the repository at https://github.com/single-spa/es.single-spa.js.org.

@codesandtags, @crorodriguezro, @diegohoyos could you do the following?

1. Accept the invitation to the repo. You should have received an email with a link. Alternatively you can go to https://github.com/single-spa/es.single-spa.js.org or https://github.com/single-spa and there should be a yellow banner at the top letting you accept the invitation.
2. Please join `#translations` in the [single-spa slack](https://join.slack.com/t/single-spa/shared_invite/enQtODAwNTIyMzc4OTE1LWUxMTUwY2M1MTY0ZGMzOTUzMGNkMzI1NzRiYzYwOWM1MTEzZDM1NDAyNWM3ZmViOTAzZThkMDcwMWZmNTFmMWQ)
3. Watch the Github repository for all activity:

![image](https://user-images.githubusercontent.com/5524384/91767441-5e218480-eb99-11ea-88b7-312d38d6b07d.png)

**Comment by internettrans** [comment]
I pull requested js.org to add the new domain - see https://github.com/js-org/js.org/pull/4601

**Comment by internettrans** [comment]
This pull request adds Spanish to the list of translations: https://github.com/single-spa/single-spa.js.org/pull/319

**Comment by internettrans** [comment]
Also  @codesandtags, @crorodriguezro, @diegohoyos could you please join the [single-spa slack](https://join.slack.com/t/single-spa/shared_invite/enQtODAwNTIyMzc4OTE1LWUxMTUwY2M1MTY0ZGMzOTUzMGNkMzI1NzRiYzYwOWM1MTEzZDM1NDAyNWM3ZmViOTAzZThkMDcwMWZmNTFmMWQ)?

And @guguji5 could you set up single-spa-bot?

**Comment by codesandtags** [comment]
Thanks @joeldenning! We are already there.

**Comment by guguji5** [comment]
@joeldenning currently, the bot help to sync the pt-pt and zh-hans repos. I am glad to transfer it to single-spa, but I don't know how to transfer across github account, today I will do a research and try.

![image](https://user-images.githubusercontent.com/17986248/91918682-35fb6800-ecf6-11ea-995c-2d23df2f3710.png)

Hi @codesandtags  , Could you apply the message(name, code and reviewers of the Spanish repo) needed by the bot, more detail is [here](https://github.com/guguji5/sync-fork-repo/blob/master/scripts/langs.js)

**Comment by guguji5** [comment]
The bot for Spanish is ready, the sync job runs in my private server currently, later I will use github action instead of it.

**Comment by internettrans** [comment]
Thanks everyone! I am closing this issue since everything is set up. Am looking forward to seeing more pull requests to es.single-spa.js.org

**Comment by guguji5** [comment]
I have checked that the bot for es is running as expected.

**Comment by codesandtags** [comment]
Hi @joeldenning 

Please could you give access to @carmudgeon to the spanish repo, I was talking with him and he is willing to help us to keep translating the documentation.

**Comment by internettrans** [comment]
Done. Welcome @carmudgeon!
