### ISSUE TITLE
quick-start / root-config module can not be opened in Chrome

### ISSUE THREAD

**Issue by volaka** [single-spa/single-spa.js.org#378]
I have followed the [Quick Start](https://single-spa.js.org/docs/getting-started-overview#quick-start) guide and tried to open it on Chrome. I received some errors. 

<img width="1006" alt="Screen Shot 2020-12-07 at 20 01 06" src="https://user-images.githubusercontent.com/13176256/101380819-0c3e7800-38c7-11eb-8c9f-975bd05d453b.png">

The page opened in Firefox without any errors.

**Comment by volaka** [comment]
Okay, the weird thing is, when I did a force reload, it rendered the page. 🤷‍♂️

**Comment by internettrans** [comment]
This sounds like unpkg.com had an error the first time you opened the app and didn't send the correct HTTP response, including CORS headers. But subsequent page loads did have the correct CORS headers from unpkg. Closing this as it seems the issue is now resolved for you. Feel free to comment further or reopen.
