### ISSUE TITLE
ES2020 TS compiler option target

### ISSUE THREAD

**Issue by MarioDena** [single-spa/single-spa.js.org#457]
tsconfig "target" does not support ES2020.

Using anything below es2017 works fine. Any chance we can change our compiler option target to ES2020 in the future?

**Comment by internettrans** [comment]
Hi @MarioDena, it's unclear what you're referring to here. This repository is for the documentation for single-spa.

The single-spa library does not require you to use typescript or change how you use typescript. Are you using the create-single-spa CLI, and referring to the typescript config created by that CLI? If so, could you be more specific about what is broken? A demonstration of the issue, or steps to reproduce would be helpful.

I am closing this as I don't know what the issue is talking about and it appears to be on the wrong repo. Feel free to comment further or reopen.

**Comment by MarioDena** [comment]
Hello @joeldenning  I though I deleted this instead of posting and moved to post on the correct repo... This was just the start of another post I did somewhere else...

Anyway sorry to bother...
