### ISSUE TITLE
Can we have a full CRA/ vue-cli/angular-cli  Example?

### ISSUE THREAD

**Issue by Jony-Y** [single-spa/single-spa.js.org#49]
Hi guys,
We have a iframe microfrontend architecture and want to run a POC with single-spa, I've tried to follow the docs and implement a few examples. But since our apps are built via the CRA and other cli's making it work still eludes me.

Could you possibly provide a full "Real world" example with CRA/CLI's? 

I wish I could give you an example of my issue. But its just too complex. basically Im trying to do something like structure wise:

```
frontend
   dashboard - CRA
   inbox - CRA
  reservstion - Angular
```

have the dashboard render a Header and the apps according to tabs. 

My Issue is that since this is a CRA and I dont control the webpack non of your examples work for me. tried adding bundled scripts but still that didnt work for me.

can you assist?

**Comment by frehner** [comment]
I think it would be great to have examples for things like this.

At the same time, it's a challenge for us to keep these examples up-to-date, since single-spa can support so many different frameworks and there's so many different clis. My biggest concern is that a significant amount of time would be spent trying to keep all those examples up-to-date.

For your situation, you must eject CRA to be able to get it to work.

**Comment by internettrans** [comment]
Yeah I agree that this would be good to have, and also challenging to keep up-to-date. I am hoping to revisit the single-spa.js.org docs after I finish single-spa-angular support.

**Comment by Jony-Y** [comment]
@frehner Are you saying it's known that you cannot work with single-spa and un ejected CRA at the moment?

**Comment by internettrans** [comment]
Yeah unejected CRA creates an HTML file, whereas in a single-spa ecosystem every application needs to produce just a javascript bundle without the HTML file (since all the applications share the [single-spa root config html file](https://single-spa.js.org/docs/configuration.html)). The solution is to eject CRA and get rid of the HTML plugin in the webpack config, along with modifying a couple other things.

**Comment by internettrans** [comment]
Btw a full angular-cli example is shown at https://github.com/CanopyTax/single-spa-angular/ and https://github.com/joeldenning/coexisting-angular-microfrontends

**Comment by filoxo** [comment]
Related: some docs for CRA was added in https://github.com/CanopyTax/single-spa.js.org/pull/72

**Comment by internettrans** [comment]
Closing since we now have some CRA docs.
